
/**
 * WDK Bundle TypeScript Declarations
 * Generated by @tetherto/wdk-worklet-bundler
 * Generated at: 2026-07-08T17:17:59.080Z
 */

export type NetworkName = 'ethereum';
export type ProtocolName = never;

export const bundle: string;
